project_id = "qdadozyjallcspeqbtlm"

[functions.parse-trip-voice]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false

[functions.cleanup-demo-data]
verify_jwt = false

[functions.sync-usgs-locations]
verify_jwt = false

[functions.water-data]
verify_jwt = false

[functions.weather]
verify_jwt = false
